services:
  cassandra1:
    image: cassandra:5.0.2
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - "9042:9042" # CQL port
      - "7000:7000" # Internode communication
      - "9160:9160" # Thrift client API
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1G
    volumes:
      - cassandra1_data:/var/lib/cassandra
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra2:
    image: cassandra:5.0.2
    container_name: cassandra2
    hostname: cassandra2
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1G
    volumes:
      - cassandra2_data:/var/lib/cassandra
    networks:
      - cassandra-net
    depends_on:
      cassandra1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra3:
    image: cassandra:5.0.2
    container_name: cassandra3
    hostname: cassandra3
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1G
    volumes:
      - cassandra3_data:/var/lib/cassandra
    networks:
      - cassandra-net
    depends_on:
      cassandra2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  cassandra1_data:
  cassandra2_data:
  cassandra3_data:

networks:
  cassandra-net:
    driver: bridge
